name: Main
on: [push, pull_request]
jobs:

  tests:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.4 1.8, 1.12, 1.16]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{matrix.go-version}}
    - name: Print go version
      run: go version
    - name: Check out module
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run tests
      run: go test -v -race ./...
