name: Main
on: [push, pull_request]
jobs:

  tests:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17, 1.16, 1.15, 1.14, 1.13, 1.12]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Install dependencies (linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libgl1-mesa-dev
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{matrix.go-version}}
    - name: Print go version
      run: go version
    - name: Check out module
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run tests
      run: go test -v -race ./...
